project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    -  "!pubs_full_list.qmd"
website:
  title: "Marcel Ferreira"
  favicon: "favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - projects.qmd
      - pubs.qmd
      - training.qmd
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

